// ============================================================
//  src/types.ts — Shared TypeScript interfaces for SignalHop
//  Updated for Phase 2: enriched IntentResult + ProductProfile
// ============================================================

import { z } from 'zod';

// ─── Database Entity ──────────────────────────────────────────

/** A project row as stored in public.projects */
export interface Project {
  id: string;
  created_at: string;
  user_id: string;
  company_name: string;
  website_url: string;
  product_context: string | null; // stored as JSON string in Supabase TEXT column
  keywords: string[];
  subreddits: string[];
  webhook_url: string;
}

// ─── Reddit Post ──────────────────────────────────────────────

/** Raw Reddit post shape parsed from RSS or JSON feed */
export interface RedditPost {
  id: string;           // e.g. "abc123"
  name: string;         // e.g. "t3_abc123" — Reddit full-name for dedup
  title: string;
  selftext: string;     // body text
  subreddit: string;
  permalink: string;    // e.g. "/r/sub/comments/abc123/title/"
  author: string;
  url: string;
  score: number;
  num_comments: number;
  created_utc: number;
}

// ─── Phase 2: Product Profile ─────────────────────────────────

/** Zod schema — used to validate raw Gemini output from contextScraper */
export const ProductProfileSchema = z.object({
  productName: z.string().min(1),
  oneLineDescription: z.string().min(1),
  targetAudience: z.array(z.string()).min(1),
  problemsSolved: z.array(z.string()).min(1),
  keywords: z.array(z.string()).min(1),
  industries: z.array(z.string()).min(1),
  customerSignals: z.array(z.string()).min(1),
});

/** Structured product profile generated by contextScraper */
export type ProductProfile = z.infer<typeof ProductProfileSchema>;

// ─── Phase 2: Intent Result ───────────────────────────────────

/** Enum of allowed intent classifications */
export const IntentTypeSchema = z.enum([
  'solution_search',
  'tool_comparison',
  'problem_complaint',
  'recommendation_request',
  'purchase_decision',
  'implementation_help',
  'general_discussion',
]);

export type IntentType = z.infer<typeof IntentTypeSchema>;

/** Enum of allowed reply styles — no personal/testimonial fabrication */
export const ReplyStyleSchema = z.enum(['educational', 'discussion', 'soft_mention']);
export type ReplyStyle = z.infer<typeof ReplyStyleSchema>;

/** A single structured reply suggestion */
export const SuggestedReplySchema = z.object({
  style: ReplyStyleSchema,
  reply: z.string().min(1),
});

export type SuggestedReply = z.infer<typeof SuggestedReplySchema>;

/** Zod schema — used to validate raw LLM output from intentProcessor */
export const IntentResultSchema = z.object({
  isHighIntent: z.boolean(),
  confidenceScore: z.number().min(0).max(1),
  priorityScore: z.number().min(0).max(100),
  intentType: IntentTypeSchema,
  buyingSignalStrength: z.number().min(0).max(10),
  painLevel: z.number().min(0).max(10),
  opportunitySummary: z.string().min(1),
  fitReason: z.string().min(1),
  suggestedReplies: z
    .tuple([SuggestedReplySchema, SuggestedReplySchema, SuggestedReplySchema]),
});

/** Structured intent classification returned by the LLM intentProcessor */
export type IntentResult = z.infer<typeof IntentResultSchema>;

// ─── Alert Payload ────────────────────────────────────────────

/** Payload dispatched to the Telegram router */
export interface AlertPayload {
  project: Project;
  post: RedditPost;
  intentResult: IntentResult;
}
